eu:
  chrost:
    cache:
      size: 5
      jpa:
        enabled: true
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    sql: DEBUG
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: TRACE
      hibernate:
        orm:
          jdbc:
            bind: TRACE